# Generated by Django 2.2.14 on 2020-08-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatchannels', '0009_auto_20200824_2320'),
        ('contacts', '0002_contact_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='chatchannels.Chat'),
            preserve_default=False,
        ),
    ]
