# Generated by Django 2.2.11 on 2020-04-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
    ]
