# Generated by Django 2.2.11 on 2020-04-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200427_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultants.Consultant', to_field='user'),
        ),
    ]
