# Generated by Django 2.2.14 on 2020-08-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatchannels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
