# Generated by Django 2.2.14 on 2020-08-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatchannels', '0004_auto_20200802_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chats',
        ),
        migrations.AddField(
            model_name='message',
            name='chats',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='chatchannels.Chat'),
        ),
    ]
