# Generated by Django 2.2.14 on 2020-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatchannels', '0008_auto_20200807_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
