# Generated by Django 2.2.14 on 2020-08-01 00:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_industry', models.CharField(max_length=50)),
                ('job_experience', models.IntegerField(default=3)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('rating', models.IntegerField(default=0)),
                ('totalsession', models.IntegerField(default=0)),
                ('is_mvp', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='consultants.Job')),
            ],
        ),
    ]
