# Generated by Django 2.2.11 on 2020-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='job_experience',
        ),
    ]
