# Generated by Django 2.2.11 on 2020-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_auto_20200404_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='linkedin',
            field=models.CharField(max_length=200),
        ),
    ]
