# Generated by Django 2.2.11 on 2020-04-03 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_auto_20200404_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='job',
        ),
        migrations.AddField(
            model_name='consultant',
            name='job',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='consultants.Job'),
            preserve_default=False,
        ),
    ]
