# Generated by Django 2.2.11 on 2020-04-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_auto_20200404_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='consultants.Job'),
        ),
    ]
