# Generated by Django 2.2.11 on 2020-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_consultant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='totalsession',
            field=models.IntegerField(default=0),
        ),
    ]
