# Generated by Django 2.2.11 on 2020-04-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_consultant_totalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultant',
            name='job_experience',
            field=models.IntegerField(default=3),
        ),
    ]
