# Generated by Django 2.2.11 on 2020-04-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_auto_20200427_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='user',
            new_name='user_id',
        ),
    ]
