# Generated by Django 2.2.11 on 2020-04-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0010_auto_20200427_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='user_id',
            new_name='user',
        ),
    ]
