# Generated by Django 2.2.11 on 2020-05-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0012_auto_20200427_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='gender',
        ),
    ]
