# Generated by Django 2.2.11 on 2020-06-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0013_remove_consultant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
